version: 1.0.{build}

branches:
  only:
  - master
  
image: Visual Studio 2017 RC

configuration: Release

environment:
  matrix:
  - SpecFlow_VisualStudioVersion: 2013
    VisualStudioVersion: 12.0
  - SpecFlow_VisualStudioVersion: 2015
    VisualStudioVersion: 14.0
  - SpecFlow_VisualStudioVersion: 2017
    VisualStudioVersion: 15.0

  
before_build:
- cmd: nuget restore SpecFlow.VisualStudio.%SpecFlow_VisualStudioVersion%.sln

build:
  project: SpecFlow.VisualStudio.%SpecFlow_VisualStudioVersion%.sln
  verbosity: minimal
  
artifacts:
- path: VsIntegration\bin\Release\TechTalk.SpecFlow.VsIntegration.2013.vsix
- path: VsIntegration\bin\Release\TechTalk.SpecFlow.VsIntegration.2015.vsix
- path: VsIntegration\bin\Release\TechTalk.SpecFlow.VsIntegration.2017.vsix