version: 1.0.{build}

branches:
  only:
    - /release.*/
    - master

configuration: Release

environment:
  matrix:
  - SpecFlow_VisualStudioVersion: 2013
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VisualStudioVersion: 12.0
  - SpecFlow_VisualStudioVersion: 2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    VisualStudioVersion: 14.0
  - SpecFlow_VisualStudioVersion: 2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VisualStudioVersion: 15.0

  
before_build:
- cmd: >-
    nuget restore SpecFlow.VisualStudio.%SpecFlow_VisualStudioVersion%.sln  
    set PATH=C:\Program Files (x86)\MSBuild\%VisualStudioVersion%\Bin;%PATH%

build:
  project: SpecFlow.VisualStudio.%SpecFlow_VisualStudioVersion%.sln
  verbosity: minimal
  
artifacts:
- path: VsIntegration\bin\Release\TechTalk.SpecFlow.VsIntegration.2013.vsix
- path: VsIntegration\bin\Release\TechTalk.SpecFlow.VsIntegration.2015.vsix
- path: VsIntegration\bin\Release\TechTalk.SpecFlow.VsIntegration.2017.vsix
